// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/my-company/petstore/internal/sdk/models/components"
	"github.com/my-company/petstore/internal/sdk/sdkinternal/utils"
)

type AddPetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	Pet *components.Pet
}

func (a AddPetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddPetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AddPetResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AddPetResponse) GetPet() *components.Pet {
	if a == nil {
		return nil
	}
	return a.Pet
}
