// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/my-company/petstore/internal/sdk/models/components"
	"github.com/my-company/petstore/internal/sdk/sdkinternal/utils"
)

type CreateUsersWithListInputResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	User *components.User
}

func (c CreateUsersWithListInputResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateUsersWithListInputResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateUsersWithListInputResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateUsersWithListInputResponse) GetUser() *components.User {
	if c == nil {
		return nil
	}
	return c.User
}
