// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lucascustodio/newteste/internal/sdk/models/components"
	"github.com/lucascustodio/newteste/internal/sdk/sdkinternal/utils"
)

type DeleteUserRequest struct {
	// The name that needs to be deleted
	Username string `pathParam:"style=simple,explode=false,name=username"`
}

func (d *DeleteUserRequest) GetUsername() string {
	if d == nil {
		return ""
	}
	return d.Username
}

type DeleteUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// User deleted
	User *components.User
}

func (d DeleteUserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteUserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteUserResponse) GetUser() *components.User {
	if d == nil {
		return nil
	}
	return d.User
}
