// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lucascustodio/newteste/internal/sdk/models/components"
	"github.com/lucascustodio/newteste/internal/sdk/sdkinternal/utils"
)

type DeleteOrderRequest struct {
	// ID of the order that needs to be deleted
	OrderID int64 `pathParam:"style=simple,explode=false,name=orderId"`
}

func (d *DeleteOrderRequest) GetOrderID() int64 {
	if d == nil {
		return 0
	}
	return d.OrderID
}

type DeleteOrderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Order deleted
	Order *components.Order
}

func (d DeleteOrderResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteOrderResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteOrderResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteOrderResponse) GetOrder() *components.Order {
	if d == nil {
		return nil
	}
	return d.Order
}
