// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lucascustodio/newteste/internal/sdk/models/components"
	"github.com/lucascustodio/newteste/internal/sdk/sdkinternal/utils"
)

type DeletePetRequest struct {
	APIKey *string `header:"style=simple,explode=false,name=api_key"`
	// Pet id to delete
	PetID int64 `pathParam:"style=simple,explode=false,name=petId"`
}

func (d *DeletePetRequest) GetAPIKey() *string {
	if d == nil {
		return nil
	}
	return d.APIKey
}

func (d *DeletePetRequest) GetPetID() int64 {
	if d == nil {
		return 0
	}
	return d.PetID
}

type DeletePetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Pet deleted
	Pet *components.Pet
}

func (d DeletePetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeletePetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeletePetResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeletePetResponse) GetPet() *components.Pet {
	if d == nil {
		return nil
	}
	return d.Pet
}
