// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lucascustodio/newteste/internal/sdk/models/components"
	"github.com/lucascustodio/newteste/internal/sdk/sdkinternal/utils"
)

type FindPetsByTagsRequest struct {
	// Tags to filter by
	Tags []string `queryParam:"style=form,explode=true,name=tags"`
}

func (f FindPetsByTagsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FindPetsByTagsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FindPetsByTagsRequest) GetTags() []string {
	if f == nil {
		return nil
	}
	return f.Tags
}

type FindPetsByTagsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	Pets []components.Pet
}

func (f FindPetsByTagsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FindPetsByTagsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FindPetsByTagsResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *FindPetsByTagsResponse) GetPets() []components.Pet {
	if f == nil {
		return nil
	}
	return f.Pets
}
