// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lucascustodio/newteste/internal/sdk/models/components"
	"github.com/lucascustodio/newteste/internal/sdk/sdkinternal/utils"
)

type GetInventoryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	Object map[string]int
}

func (g GetInventoryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetInventoryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetInventoryResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetInventoryResponse) GetObject() map[string]int {
	if g == nil {
		return nil
	}
	return g.Object
}
