// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/my-company/petstore/internal/sdk/models/components"
	"github.com/my-company/petstore/internal/sdk/sdkinternal/utils"
)

type GetOrderByIDRequest struct {
	// ID of order that needs to be fetched
	OrderID int64 `pathParam:"style=simple,explode=false,name=orderId"`
}

func (g *GetOrderByIDRequest) GetOrderID() int64 {
	if g == nil {
		return 0
	}
	return g.OrderID
}

type GetOrderByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	Order *components.Order
}

func (g GetOrderByIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetOrderByIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetOrderByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetOrderByIDResponse) GetOrder() *components.Order {
	if g == nil {
		return nil
	}
	return g.Order
}
