// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/my-company/petstore/internal/sdk/models/components"
	"github.com/my-company/petstore/internal/sdk/sdkinternal/utils"
)

type GetPetByIDRequest struct {
	// ID of pet to return
	PetID int64 `pathParam:"style=simple,explode=false,name=petId"`
}

func (g *GetPetByIDRequest) GetPetID() int64 {
	if g == nil {
		return 0
	}
	return g.PetID
}

type GetPetByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	Pet *components.Pet
}

func (g GetPetByIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPetByIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPetByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPetByIDResponse) GetPet() *components.Pet {
	if g == nil {
		return nil
	}
	return g.Pet
}
