// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lucascustodio/newteste/internal/sdk/models/components"
	"github.com/lucascustodio/newteste/internal/sdk/sdkinternal/utils"
)

type GetUserByNameRequest struct {
	// The name that needs to be fetched. Use user1 for testing.
	Username string `pathParam:"style=simple,explode=false,name=username"`
}

func (g *GetUserByNameRequest) GetUsername() string {
	if g == nil {
		return ""
	}
	return g.Username
}

type GetUserByNameResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	User *components.User
}

func (g GetUserByNameResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUserByNameResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetUserByNameResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetUserByNameResponse) GetUser() *components.User {
	if g == nil {
		return nil
	}
	return g.User
}
