// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/my-company/petstore/internal/sdk/models/components"
)

type LoginUserRequest struct {
	// The user name for login
	Username *string `queryParam:"style=form,explode=true,name=username"`
	// The password for login in clear text
	Password *string `queryParam:"style=form,explode=true,name=password"`
}

func (l *LoginUserRequest) GetUsername() *string {
	if l == nil {
		return nil
	}
	return l.Username
}

func (l *LoginUserRequest) GetPassword() *string {
	if l == nil {
		return nil
	}
	return l.Password
}

type LoginUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	String  *string
	Headers map[string][]string
}

func (l *LoginUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *LoginUserResponse) GetString() *string {
	if l == nil {
		return nil
	}
	return l.String
}

func (l *LoginUserResponse) GetHeaders() map[string][]string {
	if l == nil {
		return map[string][]string{}
	}
	return l.Headers
}
