// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/lucascustodio/newteste/internal/sdk/models/components"
	"github.com/lucascustodio/newteste/internal/sdk/sdkinternal/utils"
)

type PlaceOrderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	Order *components.Order
}

func (p PlaceOrderResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlaceOrderResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlaceOrderResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PlaceOrderResponse) GetOrder() *components.Order {
	if p == nil {
		return nil
	}
	return p.Order
}
