// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/my-company/petstore/internal/sdk/models/components"
	"github.com/my-company/petstore/internal/sdk/sdkinternal/utils"
)

type UpdatePetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	Pet *components.Pet
}

func (u UpdatePetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePetResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdatePetResponse) GetPet() *components.Pet {
	if u == nil {
		return nil
	}
	return u.Pet
}
