// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/my-company/petstore/internal/sdk/models/components"
	"github.com/my-company/petstore/internal/sdk/sdkinternal/utils"
)

type UpdateUserRequest struct {
	// name that needs to be updated
	Username string `pathParam:"style=simple,explode=false,name=username"`
	// Update an existent user in the store
	Body *components.User `request:"mediaType=application/json"`
}

func (u UpdateUserRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateUserRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateUserRequest) GetUsername() string {
	if u == nil {
		return ""
	}
	return u.Username
}

func (u *UpdateUserRequest) GetBody() *components.User {
	if u == nil {
		return nil
	}
	return u.Body
}

type UpdateUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (u *UpdateUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}
