// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/my-company/petstore/internal/sdk/models/components"
	"github.com/my-company/petstore/internal/sdk/sdkinternal/utils"
)

type UploadFileRequest struct {
	// ID of pet to update
	PetID int64 `pathParam:"style=simple,explode=false,name=petId"`
	// Additional Metadata
	AdditionalMetadata *string `queryParam:"style=form,explode=true,name=additionalMetadata"`
	Body               []byte  `request:"mediaType=application/octet-stream"`
}

func (u *UploadFileRequest) GetPetID() int64 {
	if u == nil {
		return 0
	}
	return u.PetID
}

func (u *UploadFileRequest) GetAdditionalMetadata() *string {
	if u == nil {
		return nil
	}
	return u.AdditionalMetadata
}

func (u *UploadFileRequest) GetBody() []byte {
	if u == nil {
		return nil
	}
	return u.Body
}

type UploadFileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	APIResponse *components.APIResponse
}

func (u UploadFileResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UploadFileResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UploadFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UploadFileResponse) GetAPIResponse() *components.APIResponse {
	if u == nil {
		return nil
	}
	return u.APIResponse
}
