// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package store

import (
	"fmt"
	"github.com/my-company/petstore/internal/client"
	"github.com/my-company/petstore/internal/flagutil"
	"github.com/my-company/petstore/internal/interactive"
	"github.com/my-company/petstore/internal/output"
	"github.com/my-company/petstore/internal/sdk"
	"github.com/my-company/petstore/internal/sdk/models/operations"
	"github.com/my-company/petstore/internal/usage"
	"github.com/spf13/cobra"
)

var deleteOrderCmdMeta = []flagutil.FlagMeta{
	{FlagName: "order-id", FieldPath: "OrderID", Kind: flagutil.FlagKindInt64, Required: true, Description: "ID of the order that needs to be deleted [required]"},
}

// initDeleteOrderCmd initializes the delete-order command.
func initDeleteOrderCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete-order",
		Short:   "Delete purchase order by ID",
		Long:    "For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors",
		Example: "  cli store delete-order --order-id 690575",
		RunE:    runDeleteOrderCmd,
		Aliases: []string{"do"},
	}
	flagutil.RegisterFlags(cmd, deleteOrderCmdMeta)
	if err := flagutil.ValidateMeta[operations.DeleteOrderRequest](deleteOrderCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for delete-order: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runDeleteOrderCmd executes the delete-order command.
func runDeleteOrderCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, deleteOrderCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, deleteOrderCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.DeleteOrderRequest](cmd, deleteOrderCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Store.DeleteOrder(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
