// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package store

import (
	"github.com/lucascustodio/newteste/internal/client"
	"github.com/lucascustodio/newteste/internal/output"
	"github.com/lucascustodio/newteste/internal/sdk"
	"github.com/lucascustodio/newteste/internal/sdk/models/operations"
	"github.com/lucascustodio/newteste/internal/usage"
	"github.com/spf13/cobra"
)

// initGetInventoryCmd initializes the get-inventory command.
func initGetInventoryCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-inventory",
		Short:   "Returns pet inventories by status",
		Long:    "Returns a map of status codes to quantities",
		Example: "  cli store get-inventory",
		RunE:    runGetInventoryCmd,
		Aliases: []string{"gi"},
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetInventoryCmd executes the get-inventory command.
func runGetInventoryCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Store.GetInventory(cmd.Context(), sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
