// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package store

import (
	"fmt"
	"github.com/my-company/petstore/internal/client"
	"github.com/my-company/petstore/internal/flagutil"
	"github.com/my-company/petstore/internal/interactive"
	"github.com/my-company/petstore/internal/output"
	"github.com/my-company/petstore/internal/sdk"
	"github.com/my-company/petstore/internal/sdk/models/operations"
	"github.com/my-company/petstore/internal/usage"
	"github.com/spf13/cobra"
)

var getOrderByIDCmdMeta = []flagutil.FlagMeta{
	{FlagName: "order-id", FieldPath: "OrderID", Kind: flagutil.FlagKindInt64, Required: true, Description: "ID of order that needs to be fetched [required]"},
}

// initGetOrderByIdCmd initializes the get-order-by-id command.
func initGetOrderByIdCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-order-by-id",
		Short:   "Find purchase order by ID",
		Long:    "For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.",
		Example: "  cli store get-order-by-id --order-id 728529",
		RunE:    runGetOrderByIdCmd,
		Aliases: []string{"gobi"},
	}
	flagutil.RegisterFlags(cmd, getOrderByIDCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetOrderByIDRequest](getOrderByIDCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-order-by-id: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetOrderByIdCmd executes the get-order-by-id command.
func runGetOrderByIdCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getOrderByIDCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getOrderByIDCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetOrderByIDRequest](cmd, getOrderByIDCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Store.GetOrderByID(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
