// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package store

import (
	"fmt"
	"github.com/my-company/petstore/internal/client"
	"github.com/my-company/petstore/internal/flagutil"
	"github.com/my-company/petstore/internal/interactive"
	"github.com/my-company/petstore/internal/output"
	"github.com/my-company/petstore/internal/sdk"
	"github.com/my-company/petstore/internal/sdk/models/components"
	"github.com/my-company/petstore/internal/sdk/models/operations"
	"github.com/my-company/petstore/internal/usage"
	"github.com/spf13/cobra"
)

var placeOrderCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindInt64, Optional: true, Description: "integer value"},
	{FlagName: "pet-id", Shorthand: "p", FieldPath: "PetID", Kind: flagutil.FlagKindInt64, Optional: true, Description: "integer value"},
	{FlagName: "quantity", FieldPath: "Quantity", Kind: flagutil.FlagKindInt64, Optional: true, Description: "integer value"},
	{FlagName: "ship-date", FieldPath: "ShipDate", Kind: flagutil.FlagKindDateTime, Optional: true, Description: "date/time value"},
	{FlagName: "status", FieldPath: "Status", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"placed", "approved", "delivered"}, Description: "Order Status (options: placed, approved, delivered)"},
	{FlagName: "complete", Shorthand: "c", FieldPath: "Complete", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
}

// initPlaceOrderCmd initializes the place-order command.
func initPlaceOrderCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "place-order",
		Short:   "Place an order for a pet",
		Long:    "Place a new order in the store",
		Example: "  cli store place-order",
		RunE:    runPlaceOrderCmd,
		Aliases: []string{"po"},
	}
	flagutil.RegisterFlags(cmd, placeOrderCmdMeta)
	if err := flagutil.ValidateMeta[components.Order](placeOrderCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for place-order: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runPlaceOrderCmd executes the place-order command.
func runPlaceOrderCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, placeOrderCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, placeOrderCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.Order](cmd, placeOrderCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Store.PlaceOrder(cmd.Context(), request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
