// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package store

import (
	"github.com/my-company/petstore/internal/usage"
	"github.com/spf13/cobra"
)

func InitStoreRoot(parent *cobra.Command) error {
	var StoreCmd = &cobra.Command{
		Use:   "store",
		Short: "Access to Petstore orders",
		Long:  "Access to Petstore orders",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initGetInventoryCmd(StoreCmd); err != nil {
		return err
	}

	if err := initPlaceOrderCmd(StoreCmd); err != nil {
		return err
	}

	if err := initGetOrderByIdCmd(StoreCmd); err != nil {
		return err
	}

	if err := initDeleteOrderCmd(StoreCmd); err != nil {
		return err
	}

	parent.AddCommand(StoreCmd)
	return nil
}
