// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package pet

import (
	"fmt"
	"github.com/my-company/petstore/internal/client"
	"github.com/my-company/petstore/internal/flagutil"
	"github.com/my-company/petstore/internal/interactive"
	"github.com/my-company/petstore/internal/output"
	"github.com/my-company/petstore/internal/sdk"
	"github.com/my-company/petstore/internal/sdk/models/components"
	"github.com/my-company/petstore/internal/sdk/models/operations"
	"github.com/my-company/petstore/internal/usage"
	"github.com/spf13/cobra"
)

var addPetCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindInt64, Optional: true, Description: "integer value"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Name", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "category", Shorthand: "c", FieldPath: "Category", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"category,omitempty"`, Description: "JSON object"},
	{FlagName: "photo-urls", Shorthand: "p", FieldPath: "PhotoUrls", Kind: flagutil.FlagKindStringArray, Required: true, Description: "[required]"},
	{FlagName: "tags", Shorthand: "t", FieldPath: "Tags", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"tags,omitempty"`, Description: "list of values"},
	{FlagName: "status", Shorthand: "s", FieldPath: "Status", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"available", "pending", "sold"}, Description: "pet status in the store (options: available, pending, sold)"},
}

// initAddPetCmd initializes the add-pet command.
func initAddPetCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "add",
		Short:   "Add a new pet to the store",
		Long:    "Add a new pet to the store",
		Example: "  cli pet add --name doggie --photo-urls '[\"<value 1>\",\"<value 2>\",\"<value 3>\"]'",
		RunE:    runAddPetCmd,
	}
	flagutil.RegisterFlags(cmd, addPetCmdMeta)
	if err := flagutil.ValidateMeta[components.Pet](addPetCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for add-pet: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runAddPetCmd executes the add-pet command.
func runAddPetCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, addPetCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, addPetCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.Pet](cmd, addPetCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Pet.AddPet(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
