// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package pet

import (
	"fmt"
	"github.com/my-company/petstore/internal/client"
	"github.com/my-company/petstore/internal/flagutil"
	"github.com/my-company/petstore/internal/interactive"
	"github.com/my-company/petstore/internal/output"
	"github.com/my-company/petstore/internal/sdk"
	"github.com/my-company/petstore/internal/sdk/models/operations"
	"github.com/my-company/petstore/internal/usage"
	"github.com/spf13/cobra"
)

var deletePetCmdMeta = []flagutil.FlagMeta{
	{FlagName: "api-key", Shorthand: "a", FieldPath: "APIKey", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "pet-id", Shorthand: "p", FieldPath: "PetID", Kind: flagutil.FlagKindInt64, Required: true, Description: "Pet id to delete [required]"},
}

// initDeletePetCmd initializes the delete-pet command.
func initDeletePetCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete",
		Short:   "Deletes a pet",
		Long:    "Deletes a pet",
		Example: "  cli pet delete --pet-id 818965",
		RunE:    runDeletePetCmd,
	}
	flagutil.RegisterFlags(cmd, deletePetCmdMeta)
	if err := flagutil.ValidateMeta[operations.DeletePetRequest](deletePetCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for delete-pet: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runDeletePetCmd executes the delete-pet command.
func runDeletePetCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, deletePetCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, deletePetCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.DeletePetRequest](cmd, deletePetCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Pet.DeletePet(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
