// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package pet

import (
	"fmt"
	"github.com/my-company/petstore/internal/client"
	"github.com/my-company/petstore/internal/flagutil"
	"github.com/my-company/petstore/internal/interactive"
	"github.com/my-company/petstore/internal/output"
	"github.com/my-company/petstore/internal/sdk"
	"github.com/my-company/petstore/internal/sdk/models/operations"
	"github.com/my-company/petstore/internal/usage"
	"github.com/spf13/cobra"
)

var findPetsByTagsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "tags", Shorthand: "t", FieldPath: "Tags", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Tags to filter by"},
}

// initFindPetsByTagsCmd initializes the find-pets-by-tags command.
func initFindPetsByTagsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "find-pets-by-tags",
		Short:   "Finds Pets by tags",
		Long:    "Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.",
		Example: "  cli pet find-pets-by-tags",
		RunE:    runFindPetsByTagsCmd,
		Aliases: []string{"fpbt"},
	}
	flagutil.RegisterFlags(cmd, findPetsByTagsCmdMeta)
	if err := flagutil.ValidateMeta[operations.FindPetsByTagsRequest](findPetsByTagsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for find-pets-by-tags: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runFindPetsByTagsCmd executes the find-pets-by-tags command.
func runFindPetsByTagsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, findPetsByTagsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, findPetsByTagsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.FindPetsByTagsRequest](cmd, findPetsByTagsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Pet.FindPetsByTags(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
