// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package pet

import (
	"fmt"
	"github.com/lucascustodio/newteste/internal/client"
	"github.com/lucascustodio/newteste/internal/flagutil"
	"github.com/lucascustodio/newteste/internal/interactive"
	"github.com/lucascustodio/newteste/internal/output"
	"github.com/lucascustodio/newteste/internal/sdk"
	"github.com/lucascustodio/newteste/internal/sdk/models/operations"
	"github.com/lucascustodio/newteste/internal/usage"
	"github.com/spf13/cobra"
)

var findPetsByStatusCmdMeta = []flagutil.FlagMeta{
	{FlagName: "status", Shorthand: "s", FieldPath: "Status", Kind: flagutil.FlagKindEnum, Optional: true, HasDefault: true, DefaultStr: "available", EnumValues: []string{"available", "pending", "sold"}, Description: "Status values that need to be considered for filter (options: available, pending, sold)"},
}

// initFindPetsByStatusCmd initializes the find-pets-by-status command.
func initFindPetsByStatusCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "find-pets-by-status",
		Short:   "Finds Pets by status",
		Long:    "Multiple status values can be provided with comma separated strings",
		Example: "  cli pet find-pets-by-status",
		RunE:    runFindPetsByStatusCmd,
		Aliases: []string{"fpbs"},
	}
	flagutil.RegisterFlags(cmd, findPetsByStatusCmdMeta)
	if err := flagutil.ValidateMeta[operations.FindPetsByStatusRequest](findPetsByStatusCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for find-pets-by-status: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runFindPetsByStatusCmd executes the find-pets-by-status command.
func runFindPetsByStatusCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, findPetsByStatusCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, findPetsByStatusCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.FindPetsByStatusRequest](cmd, findPetsByStatusCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Pet.FindPetsByStatus(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
