// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package pet

import (
	"fmt"
	"github.com/lucascustodio/newteste/internal/client"
	"github.com/lucascustodio/newteste/internal/flagutil"
	"github.com/lucascustodio/newteste/internal/interactive"
	"github.com/lucascustodio/newteste/internal/output"
	"github.com/lucascustodio/newteste/internal/sdk"
	"github.com/lucascustodio/newteste/internal/sdk/models/operations"
	"github.com/lucascustodio/newteste/internal/usage"
	"github.com/spf13/cobra"
)

var getPetByIDCmdMeta = []flagutil.FlagMeta{
	{FlagName: "pet-id", Shorthand: "p", FieldPath: "PetID", Kind: flagutil.FlagKindInt64, Required: true, Description: "ID of pet to return [required]"},
}

// initGetPetByIdCmd initializes the get-pet-by-id command.
func initGetPetByIdCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-pet-by-id",
		Short:   "Find pet by ID",
		Long:    "Returns a single pet",
		Example: "  cli pet get-pet-by-id --pet-id 311674",
		RunE:    runGetPetByIdCmd,
		Aliases: []string{"gpbi"},
	}
	flagutil.RegisterFlags(cmd, getPetByIDCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetPetByIDRequest](getPetByIDCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-pet-by-id: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetPetByIdCmd executes the get-pet-by-id command.
func runGetPetByIdCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getPetByIDCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getPetByIDCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetPetByIDRequest](cmd, getPetByIDCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Pet.GetPetByID(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
