// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package pet

import (
	"github.com/lucascustodio/newteste/internal/usage"
	"github.com/spf13/cobra"
)

func InitPetRoot(parent *cobra.Command) error {
	var PetCmd = &cobra.Command{
		Use:   "pet",
		Short: "Everything about your Pets",
		Long:  "Everything about your Pets",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initUpdatePetCmd(PetCmd); err != nil {
		return err
	}

	if err := initAddPetCmd(PetCmd); err != nil {
		return err
	}

	if err := initFindPetsByStatusCmd(PetCmd); err != nil {
		return err
	}

	if err := initFindPetsByTagsCmd(PetCmd); err != nil {
		return err
	}

	if err := initGetPetByIdCmd(PetCmd); err != nil {
		return err
	}

	if err := initDeletePetCmd(PetCmd); err != nil {
		return err
	}

	if err := initUploadFileCmd(PetCmd); err != nil {
		return err
	}

	parent.AddCommand(PetCmd)
	return nil
}
