// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package pet

import (
	"fmt"
	"github.com/lucascustodio/newteste/internal/client"
	"github.com/lucascustodio/newteste/internal/flagutil"
	"github.com/lucascustodio/newteste/internal/interactive"
	"github.com/lucascustodio/newteste/internal/output"
	"github.com/lucascustodio/newteste/internal/sdk"
	"github.com/lucascustodio/newteste/internal/sdk/models/operations"
	"github.com/lucascustodio/newteste/internal/usage"
	"github.com/spf13/cobra"
)

var uploadFileCmdMeta = []flagutil.FlagMeta{
	{FlagName: "pet-id", Shorthand: "p", FieldPath: "PetID", Kind: flagutil.FlagKindInt64, Required: true, Description: "ID of pet to update [required]"},
	{FlagName: "additional-metadata", Shorthand: "a", FieldPath: "AdditionalMetadata", Kind: flagutil.FlagKindString, Optional: true, Description: "Additional Metadata"},
	{FlagName: "body-param", Shorthand: "b", FieldPath: "Body", Kind: flagutil.FlagKindBytes, Optional: true, Description: "binary data (file:<path> or b64:<base64>)"},
}

// initUploadFileCmd initializes the upload-file command.
func initUploadFileCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "upload-file",
		Short:   "uploads an image",
		Long:    "uploads an image",
		Example: "  cli pet upload-file --pet-id 150516",
		RunE:    runUploadFileCmd,
		Aliases: []string{"uf"},
	}
	flagutil.RegisterFlags(cmd, uploadFileCmdMeta)
	if err := flagutil.ValidateMeta[operations.UploadFileRequest](uploadFileCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for upload-file: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runUploadFileCmd executes the upload-file command.
func runUploadFileCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, uploadFileCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, uploadFileCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.UploadFileRequest](cmd, uploadFileCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Pet.UploadFile(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
