// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Category struct {
	ID   *int64  `json:"id,omitzero"`
	Name *string `json:"name,omitzero"`
}

func (c *Category) GetID() *int64 {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *Category) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}
