// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/my-company/petstore/internal/sdk/sdkinternal/utils"
	"time"
)

// OrderStatus - Order Status
type OrderStatus string

const (
	OrderStatusPlaced    OrderStatus = "placed"
	OrderStatusApproved  OrderStatus = "approved"
	OrderStatusDelivered OrderStatus = "delivered"
)

func (e OrderStatus) ToPointer() *OrderStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OrderStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "placed", "approved", "delivered":
			return true
		}
	}
	return false
}

type Order struct {
	ID       *int64     `json:"id,omitzero"`
	PetID    *int64     `json:"petId,omitzero"`
	Quantity *int       `json:"quantity,omitzero"`
	ShipDate *time.Time `json:"shipDate,omitzero"`
	// Order Status
	Status   *OrderStatus `json:"status,omitzero"`
	Complete *bool        `json:"complete,omitzero"`
}

func (o Order) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *Order) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *Order) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Order) GetPetID() *int64 {
	if o == nil {
		return nil
	}
	return o.PetID
}

func (o *Order) GetQuantity() *int {
	if o == nil {
		return nil
	}
	return o.Quantity
}

func (o *Order) GetShipDate() *time.Time {
	if o == nil {
		return nil
	}
	return o.ShipDate
}

func (o *Order) GetStatus() *OrderStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *Order) GetComplete() *bool {
	if o == nil {
		return nil
	}
	return o.Complete
}
