// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/lucascustodio/newteste/internal/sdk/sdkinternal/utils"
)

// PetStatus - pet status in the store
type PetStatus string

const (
	PetStatusAvailable PetStatus = "available"
	PetStatusPending   PetStatus = "pending"
	PetStatusSold      PetStatus = "sold"
)

func (e PetStatus) ToPointer() *PetStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PetStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "available", "pending", "sold":
			return true
		}
	}
	return false
}

type Pet struct {
	ID        *int64    `json:"id,omitzero"`
	Name      string    `json:"name"`
	Category  *Category `json:"category,omitzero"`
	PhotoUrls []string  `json:"photoUrls"`
	Tags      []Tag     `json:"tags,omitzero"`
	// pet status in the store
	Status *PetStatus `json:"status,omitzero"`
}

func (p Pet) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Pet) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Pet) GetID() *int64 {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *Pet) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *Pet) GetCategory() *Category {
	if p == nil {
		return nil
	}
	return p.Category
}

func (p *Pet) GetPhotoUrls() []string {
	if p == nil {
		return []string{}
	}
	return p.PhotoUrls
}

func (p *Pet) GetTags() []Tag {
	if p == nil {
		return nil
	}
	return p.Tags
}

func (p *Pet) GetStatus() *PetStatus {
	if p == nil {
		return nil
	}
	return p.Status
}
