// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Tag struct {
	ID   *int64  `json:"id,omitzero"`
	Name *string `json:"name,omitzero"`
}

func (t *Tag) GetID() *int64 {
	if t == nil {
		return nil
	}
	return t.ID
}

func (t *Tag) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}
