// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type User struct {
	ID        *int64  `json:"id,omitzero"`
	Username  *string `json:"username,omitzero"`
	FirstName *string `json:"firstName,omitzero"`
	LastName  *string `json:"lastName,omitzero"`
	Email     *string `json:"email,omitzero"`
	Password  *string `json:"password,omitzero"`
	Phone     *string `json:"phone,omitzero"`
	// User Status
	UserStatus *int `json:"userStatus,omitzero"`
}

func (u *User) GetID() *int64 {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *User) GetUsername() *string {
	if u == nil {
		return nil
	}
	return u.Username
}

func (u *User) GetFirstName() *string {
	if u == nil {
		return nil
	}
	return u.FirstName
}

func (u *User) GetLastName() *string {
	if u == nil {
		return nil
	}
	return u.LastName
}

func (u *User) GetEmail() *string {
	if u == nil {
		return nil
	}
	return u.Email
}

func (u *User) GetPassword() *string {
	if u == nil {
		return nil
	}
	return u.Password
}

func (u *User) GetPhone() *string {
	if u == nil {
		return nil
	}
	return u.Phone
}

func (u *User) GetUserStatus() *int {
	if u == nil {
		return nil
	}
	return u.UserStatus
}
