// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package user

import (
	"fmt"
	"github.com/lucascustodio/newteste/internal/client"
	"github.com/lucascustodio/newteste/internal/flagutil"
	"github.com/lucascustodio/newteste/internal/interactive"
	"github.com/lucascustodio/newteste/internal/output"
	"github.com/lucascustodio/newteste/internal/sdk"
	"github.com/lucascustodio/newteste/internal/sdk/models/components"
	"github.com/lucascustodio/newteste/internal/sdk/models/operations"
	"github.com/lucascustodio/newteste/internal/usage"
	"github.com/spf13/cobra"
)

var createUserCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindInt64, Optional: true, Description: "integer value"},
	{FlagName: "username", FieldPath: "Username", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "first-name", Shorthand: "f", FieldPath: "FirstName", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "last-name", Shorthand: "l", FieldPath: "LastName", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "email", Shorthand: "e", FieldPath: "Email", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "password", FieldPath: "Password", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "phone", FieldPath: "Phone", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "user-status", FieldPath: "UserStatus", Kind: flagutil.FlagKindInt64, Optional: true, Description: "User Status"},
}

// initCreateUserCmd initializes the create-user command.
func initCreateUserCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create user",
		Long:    "This can only be done by the logged in user.",
		Example: "  cli user create",
		RunE:    runCreateUserCmd,
	}
	flagutil.RegisterFlags(cmd, createUserCmdMeta)
	if err := flagutil.ValidateMeta[components.User](createUserCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-user: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateUserCmd executes the create-user command.
func runCreateUserCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createUserCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createUserCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.User](cmd, createUserCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.User.CreateUser(cmd.Context(), request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
