// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package user

import (
	"github.com/lucascustodio/newteste/internal/client"
	"github.com/lucascustodio/newteste/internal/flagutil"
	"github.com/lucascustodio/newteste/internal/interactive"
	"github.com/lucascustodio/newteste/internal/output"
	"github.com/lucascustodio/newteste/internal/sdk"
	"github.com/lucascustodio/newteste/internal/sdk/models/components"
	"github.com/lucascustodio/newteste/internal/sdk/models/operations"
	"github.com/lucascustodio/newteste/internal/usage"
	"github.com/spf13/cobra"
)

// initCreateUsersWithListInputCmd initializes the create-users-with-list-input command.
func initCreateUsersWithListInputCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create-users-with-list-input",
		Short:   "Creates list of users with given input array",
		Long:    "Creates list of users with given input array",
		Example: "  cli user create-users-with-list-input --request '[{\"id\":10,\"username\":\"theUser\",\"firstName\":\"John\",\"lastName\":\"James\",\"email\":\"john@email.com\",\"password\":\"12345\",\"phone\":\"12345\",\"userStatus\":1}]'",
		RunE:    runCreateUsersWithListInputCmd,
		Aliases: []string{"cuwli"},
	}
	cmd.Flags().String("request", "", "Request body as JSON. Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateUsersWithListInputCmd executes the create-users-with-list-input command.
func runCreateUsersWithListInputCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPromptForBody(cmd, "request") {
		if err := interactive.PromptForBodyJSON(cmd, "request", "Request body as JSON. Can also be provided via stdin."); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequestBody[[]components.User](cmd, "request", `request:"mediaType=application/json"`, false)
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.User.CreateUsersWithListInput(cmd.Context(), flagutil.DerefOrZero(request), sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
