// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package user

import (
	"fmt"
	"github.com/my-company/petstore/internal/client"
	"github.com/my-company/petstore/internal/flagutil"
	"github.com/my-company/petstore/internal/interactive"
	"github.com/my-company/petstore/internal/output"
	"github.com/my-company/petstore/internal/sdk"
	"github.com/my-company/petstore/internal/sdk/models/operations"
	"github.com/my-company/petstore/internal/usage"
	"github.com/spf13/cobra"
)

var deleteUserCmdMeta = []flagutil.FlagMeta{
	{FlagName: "username", Shorthand: "u", FieldPath: "Username", Kind: flagutil.FlagKindString, Required: true, Description: "The name that needs to be deleted [required]"},
}

// initDeleteUserCmd initializes the delete-user command.
func initDeleteUserCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete",
		Short:   "Delete user",
		Long:    "This can only be done by the logged in user.",
		Example: "  cli user delete --username Rita_Schuppe",
		RunE:    runDeleteUserCmd,
	}
	flagutil.RegisterFlags(cmd, deleteUserCmdMeta)
	if err := flagutil.ValidateMeta[operations.DeleteUserRequest](deleteUserCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for delete-user: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runDeleteUserCmd executes the delete-user command.
func runDeleteUserCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, deleteUserCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, deleteUserCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.DeleteUserRequest](cmd, deleteUserCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.User.DeleteUser(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
