// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package user

import (
	"fmt"
	"github.com/my-company/petstore/internal/client"
	"github.com/my-company/petstore/internal/flagutil"
	"github.com/my-company/petstore/internal/interactive"
	"github.com/my-company/petstore/internal/output"
	"github.com/my-company/petstore/internal/sdk"
	"github.com/my-company/petstore/internal/sdk/models/operations"
	"github.com/my-company/petstore/internal/usage"
	"github.com/spf13/cobra"
)

var getUserByNameCmdMeta = []flagutil.FlagMeta{
	{FlagName: "username", Shorthand: "u", FieldPath: "Username", Kind: flagutil.FlagKindString, Required: true, Description: "The name that needs to be fetched. Use user1 for testing.  [required]"},
}

// initGetUserByNameCmd initializes the get-user-by-name command.
func initGetUserByNameCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-user-by-name",
		Short:   "Get user by user name",
		Long:    "Get user by user name",
		Example: "  cli user get-user-by-name --username Edyth10",
		RunE:    runGetUserByNameCmd,
		Aliases: []string{"gubn"},
	}
	flagutil.RegisterFlags(cmd, getUserByNameCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetUserByNameRequest](getUserByNameCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-user-by-name: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetUserByNameCmd executes the get-user-by-name command.
func runGetUserByNameCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getUserByNameCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getUserByNameCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetUserByNameRequest](cmd, getUserByNameCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.User.GetUserByName(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
