// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package user

import (
	"fmt"
	"github.com/lucascustodio/newteste/internal/client"
	"github.com/lucascustodio/newteste/internal/flagutil"
	"github.com/lucascustodio/newteste/internal/interactive"
	"github.com/lucascustodio/newteste/internal/output"
	"github.com/lucascustodio/newteste/internal/sdk"
	"github.com/lucascustodio/newteste/internal/sdk/models/operations"
	"github.com/lucascustodio/newteste/internal/usage"
	"github.com/spf13/cobra"
)

var loginUserCmdMeta = []flagutil.FlagMeta{
	{FlagName: "username", Shorthand: "u", FieldPath: "Username", Kind: flagutil.FlagKindString, Optional: true, Description: "The user name for login"},
	{FlagName: "password", Shorthand: "p", FieldPath: "Password", Kind: flagutil.FlagKindString, Optional: true, Description: "The password for login in clear text"},
}

// initLoginUserCmd initializes the login-user command.
func initLoginUserCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "login",
		Short:   "Logs user into the system",
		Long:    "Logs user into the system",
		Example: "  cli user login",
		RunE:    runLoginUserCmd,
	}
	flagutil.RegisterFlags(cmd, loginUserCmdMeta)
	if err := flagutil.ValidateMeta[operations.LoginUserRequest](loginUserCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for login-user: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runLoginUserCmd executes the login-user command.
func runLoginUserCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, loginUserCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, loginUserCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.LoginUserRequest](cmd, loginUserCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.User.LoginUser(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
