// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package user

import (
	"github.com/my-company/petstore/internal/client"
	"github.com/my-company/petstore/internal/output"
	"github.com/my-company/petstore/internal/sdk"
	"github.com/my-company/petstore/internal/sdk/models/operations"
	"github.com/my-company/petstore/internal/usage"
	"github.com/spf13/cobra"
)

// initLogoutUserCmd initializes the logout-user command.
func initLogoutUserCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "logout",
		Short:   "Logs out current logged in user session",
		Long:    "Logs out current logged in user session",
		Example: "  cli user logout",
		RunE:    runLogoutUserCmd,
	}
	parent.AddCommand(cmd)
	return nil
}

// runLogoutUserCmd executes the logout-user command.
func runLogoutUserCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.User.LogoutUser(cmd.Context(), sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
