// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package user

import (
	"github.com/lucascustodio/newteste/internal/usage"
	"github.com/spf13/cobra"
)

func InitUserRoot(parent *cobra.Command) error {
	var UserCmd = &cobra.Command{
		Use:   "user",
		Short: "Operations about user",
		Long:  "Operations about user",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initCreateUserCmd(UserCmd); err != nil {
		return err
	}

	if err := initCreateUsersWithListInputCmd(UserCmd); err != nil {
		return err
	}

	if err := initLoginUserCmd(UserCmd); err != nil {
		return err
	}

	if err := initLogoutUserCmd(UserCmd); err != nil {
		return err
	}

	if err := initGetUserByNameCmd(UserCmd); err != nil {
		return err
	}

	if err := initUpdateUserCmd(UserCmd); err != nil {
		return err
	}

	if err := initDeleteUserCmd(UserCmd); err != nil {
		return err
	}

	parent.AddCommand(UserCmd)
	return nil
}
