// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package user

import (
	"fmt"
	"github.com/lucascustodio/newteste/internal/client"
	"github.com/lucascustodio/newteste/internal/flagutil"
	"github.com/lucascustodio/newteste/internal/interactive"
	"github.com/lucascustodio/newteste/internal/output"
	"github.com/lucascustodio/newteste/internal/sdk"
	"github.com/lucascustodio/newteste/internal/sdk/models/operations"
	"github.com/lucascustodio/newteste/internal/usage"
	"github.com/spf13/cobra"
)

var updateUserCmdMeta = []flagutil.FlagMeta{
	{FlagName: "username", Shorthand: "u", FieldPath: "Username", Kind: flagutil.FlagKindString, Required: true, Description: "name that needs to be updated [required]"},
	{FlagName: "body-param.id", FieldPath: "Body.ID", Kind: flagutil.FlagKindInt64, Optional: true, Description: "integer value"},
	{FlagName: "body-param.username", FieldPath: "Body.Username", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "body-param.first-name", FieldPath: "Body.FirstName", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "body-param.last-name", FieldPath: "Body.LastName", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "body-param.email", FieldPath: "Body.Email", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "body-param.password", FieldPath: "Body.Password", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "body-param.phone", FieldPath: "Body.Phone", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "body-param.user-status", FieldPath: "Body.UserStatus", Kind: flagutil.FlagKindInt64, Optional: true, Description: "User Status"},
}

// initUpdateUserCmd initializes the update-user command.
func initUpdateUserCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update",
		Short:   "Update user",
		Long:    "This can only be done by the logged in user.",
		Example: "  cli user update --username Alison.Cassin",
		RunE:    runUpdateUserCmd,
	}
	flagutil.RegisterFlags(cmd, updateUserCmdMeta)
	if err := flagutil.ValidateMeta[operations.UpdateUserRequest](updateUserCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for update-user: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runUpdateUserCmd executes the update-user command.
func runUpdateUserCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, updateUserCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, updateUserCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.UpdateUserRequest](cmd, updateUserCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.User.UpdateUser(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
